# Generated by Django 4.2.7 on 2023-11-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirius_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.CharField(verbose_name='Картинка'),
        ),
    ]
